### ISSUE TITLE
Add results screen to prototype

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#11]
![image](https://user-images.githubusercontent.com/16842122/61759475-68aa0180-ad7d-11e9-9c1f-f63f485ec4db.png)

Testing stuff

**Comment by jaanjah** [comment]
Add the features the result screen should have to this issue please. Thanks :)

**Comment by dustdustinthewind** [comment]
Hahaha, I did this as the first issue as a test, but sure I'll add them!

Final Score
Max Combo
Accuracy
Judgement counter, (number of MAXs, Perfects, Goods, etc.)

I believe are the minimum we need to count as a working prototype screen.

**Comment by dustdustinthewind** [comment]
Working Result Screen has been in the prototype for a week now, I guess I can close this now? Especially since this issue was sort of a test/joke thing lol.
