### ISSUE TITLE
Split Leaderboards

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#18]
Along with as there being an overall leaderboard, allow users to set their default leaderboard based on different play styles or settings.

~~https://discordapp.com/channels/600885985219444741/600886496677068825/600915704782520331~~
Edit: Image Reference
![image](https://user-images.githubusercontent.com/16842122/61771039-9609a600-ada3-11e9-92f1-c34c69f68b0a.png)

**Comment by jaanjah** [comment]
Could you elaborate what those different playstyles or settings would be?

**Comment by dustdustinthewind** [comment]
Yeah!

So in the Intralism community there has been some minor controversy about the use of camera-distance changes (or "zooms") in maps. [Reference Video on zooms.](https://youtu.be/HpxeQtv9NCg) Some players really dislike zooms and would like an option to turn them off, but other players love them and want them to stay enabled. I think that players should deserve the option to turn off zooms, but there is a valid argument about how reading a map with zooms takes a different kind of skill than other rhythm games. If you give players the option to disable zooms, then the best way to play maps competitively would to turn off zooms.

So as a compromise, I think if we designed the Ranking system to consider zoom in a map. If a player turns off zoom, their rank score would be calculated without zoom into consideration. A player who has zoom on will have a rank score that was calculated with zoom. So, it's likely that zoom players would gain more ranked points than no-zoom players. I like this idea of a modular ranking system based on user settings, but I could also see this enforcing a "Zoom" meta, which is the opposite problem as the "zoomless" meta before. Having a split leaderboard I think would encourage to play how they want without feeling like they're at a disadvantage or "playing incorrectly". You can set up a default leaderboard for yourself to display your rank compared to other non-zoom players, instead of only having the overall leaderboard as the only option for your profile.

The other big thing is there has been some minor controversy about players who played Intralism one-handed versus those who played two-handed. Two-handed play is competitively more viable, but some one-handed players got discouraged from playing the game because the two-handed players were dominating the leaderboards. A split leaderboard could be helpful here too, for similar reasons as the zoom/non-zoom thing.

Multiple key-modes would be another place for a split leaderboard. I remember a lot of people in o!m being upset that they had to be on the same leaderboard as players who played with different keys.

**Comment by jaanjah** [comment]
> Yeah!
> 
> So in the Intralism community there has been some minor controversy about the use of camera-distance changes (or "zooms") in maps. [Reference Video on zooms.](https://youtu.be/HpxeQtv9NCg) Some players really dislike zooms and would like an option to turn them off, but other players love them and want them to stay enabled. I think that players should deserve the option to turn off zooms, but there is a valid argument about how reading a map with zooms takes a different kind of skill than other rhythm games. If you give players the option to disable zooms, then the best way to play maps competitively would to turn off zooms.
> 
> So as a compromise, I think if we designed the Ranking system to consider zoom in a map. If a player turns off zoom, their rank score would be calculated without zoom into consideration. A player who has zoom on will have a rank score that was calculated with zoom. So, it's likely that zoom players would gain more ranked points than no-zoom players. I like this idea of a modular ranking system based on user settings, but I could also see this enforcing a "Zoom" meta, which is the opposite problem as the "zoomless" meta before. Having a split leaderboard I think would encourage to play how they want without feeling like they're at a disadvantage or "playing incorrectly". You can set up a default leaderboard for yourself to display your rank compared to other non-zoom players, instead of only having the overall leaderboard as the only option for your profile.
> 
> The other big thing is there has been some minor controversy about players who played Intralism one-handed versus those who played two-handed. Two-handed play is competitively more viable, but some one-handed players got discouraged from playing the game because the two-handed players were dominating the leaderboards. A split leaderboard could be helpful here too, for similar reasons as the zoom/non-zoom thing.
> 
> Multiple key-modes would be another place for a split leaderboard. I remember a lot of people in o!m being upset that they had to be on the same leaderboard as players who played with different keys.

I think it's not a good idea to give more ranked points to zoom or less to non-zoom players. Maybe we could add a no-zoom mod which just disables zooming and leaves the score unranked.

Also how are you going to check if the player is playing one or two-handed, i don't think it needs to be 2 separate categories in the leaderboard. Two-handed players could just dominate one-handed leaderboards if they wanted to.

**Comment by dustdustinthewind** [comment]
Yeah, trying to figure out 1-hand or 2-handed players would be challenging, and there doesn't seem to be a neat way to figure it out honestly. One idea is to see what keys are being pressed, but that can be spoofed with software, and some 2-handed players play with the same keys a 1-handed player would (AWSD/Arrow Keys).

Edit: I also agree that if we don't do a rank-split or similar, then the option _should_ be an option, at least for practice/unranked.

**Comment by jaanjah** [comment]
> Yeah, trying to figure out 1-hand or 2-handed players would be challenging, and there doesn't seem to be a neat way to figure it out honestly. One idea is to see what keys are being pressed, but that can be spoofed with software, and some 2-handed players play with the same keys a 1-handed player would (AWSD/Arrow Keys).
> 
> Edit: I also agree that if we don't do a rank-split or similar, then the option _should_ be an option, at least for practice/unranked.

In the VSRG community I come from, we just have one-handed and two-handed players in the same category/leaderboard, people just record and upload to youtube showing their playstyle. In the community we also have a playstyle called Index, where player uses 2 index fingers to play. But I think keeping 1/2 handed players in the same category.

We can split leaderboards for mods that differ the gameplay I guess, maybe something like Hard Rock or Flashlight on osu!

**Comment by dustdustinthewind** [comment]
Fixing up issues to be more serious and present-focused. Will re-open when needed.

Thanks for the discussion so far Jaan.
