### ISSUE TITLE
Zooms

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#29]
Known as "Camera Distance" in Intralism's editor, this is a gameplay option that effects the playfield in a way that looks like the crosshair and related gameplay elements are closer or farther away from the screen. There have been a mapping style created in the Intralism community, a style that uses this zoom effect for cosmetic and gameplay reasons. As a "Zoom-Mapper" from Intralism's community myself, I think zooms provide plenty of new gameplay that other rhythm games can't offer. I also think zooms can be further refined, to the point where zooms are as much a gameplay element as arcs and timing are. Kara Kara Kara no Kara was a map that I created in Intralism, that applied this philosophy of using "Zoom" as a gameplay element and not just for cosmetics. This is a feature that was just starting to get explored in Intralism, and it should not be left behind.

Examples of Zoom in Intralism:
[Kara Kara](https://youtu.be/HpxeQtv9NCg)
[Alcohol Poisoning Challenge](https://youtu.be/DkwbEN6_254)

**Comment by jaanjah** [comment]
Could you send an example how it looks like, so we have a reference what should be the goal be of this feature :)

**Comment by dustdustinthewind** [comment]
LMFAO I forgot to link these earlier my bad!

Kara Kara, my attempt at zoom-focused map: https://youtu.be/HpxeQtv9NCg NOTE: It is very repetitive until 2:55, where I start using other gimmicks besides the "thump". Also it's hard to notice but between 2:55 and 3:25 zoom changes very slowly.

Nauseating Gimmick, known as the "Alcohol Poisoning Challenge," Where each lane was given a different scroll speed, and every arc randomly changed the zoom: https://youtu.be/DkwbEN6_254

**Comment by Adrriii** [comment]
Added a Camera2D feature in the ResultScreen branch, which will be useful for this feature. We need to find a formula to replicate intralism as precisely as possible.

**Comment by dustdustinthewind** [comment]
Currently have Intralizoom implentation, basic linear and step zooms implemented. Will work on more zoom types alongside the development of the editor, and we'll use new, more specific issues for those.
