### ISSUE TITLE
Set Up Main Menu

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#30]
The main menu needs to be the first screen that the user sees. The main menu needs buttons that can direct the user to the Map Select, the Options Menu, and the Editor.
Social Media and Multiplayer buttons aren't as important but can be worked on as well. Multiplayer will not be worked on for a while, so have a "Not Ready" hover message or similar. Social Media would just be the Development Discord server and Github for now.

**Comment by jaanjah** [comment]
Perhaps add a template how it should look like in this issue.

**Comment by dustdustinthewind** [comment]
Apologies! There has been some discussion about this on discord, and this is the design Makaii and @rubiksmaster02 have been working on, Makaii with art and rubiks has been working on coding this.
![image](https://user-images.githubusercontent.com/16842122/61977804-4e9e3800-afa4-11e9-85a1-855875005ac7.png)
The background image will be changed, just a placeholder image for now.

Assets from the image: 
[playgameassets.zip](https://github.com/PulsarcGame/Pulsarc/files/3437231/playgameassets.zip)

**Comment by jaanjah** [comment]
> Apologies! There has been some discussion about this on discord, and this is the design Makaii and @rubiksmaster02 have been working on, Makaii with art and rubiks has been working on coding this.
> ![image](https://user-images.githubusercontent.com/16842122/61977804-4e9e3800-afa4-11e9-85a1-855875005ac7.png)
> The background image will be changed, just a placeholder image for now.
> 
> Assets from the image:
> [playgameassets.zip](https://github.com/PulsarcGame/Pulsarc/files/3437231/playgameassets.zip)

Make sure they will make a pull request after @rubiksmaster02 is done implementing this, so we can do code review and merge it.

**Comment by Adrriii** [comment]
regarding the assets : 
since it's a main menu, we might need to add different Locals support in the future. Which means we would write using a spritefont on possibly different blank buttons, instead of having the text directly on the images.
