### ISSUE TITLE
Create Basic Objects for the Option Menu

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#31]
Here's what I think we need:

**Slider**: for options that use percentages (Volume, Background dim, etc.)
Example from Intralism: 
![image](https://user-images.githubusercontent.com/16842122/61921275-742e3180-af11-11e9-93d6-07f8b9407743.png)

**DropDownList**: for listed options (Skin Select, Resolution Settings, etc.)
Example from osu: 
![image](https://user-images.githubusercontent.com/16842122/61921372-cbcc9d00-af11-11e9-843d-592c993b39e4.png)

**CheckBox**: For binary options, yes/no, true/false, enable/disable, etc. (Basically every other option)
Example from osu:
![image](https://user-images.githubusercontent.com/16842122/61921399-df780380-af11-11e9-8f04-c07dc8b118ae.png)

These options should read and modify variables inside a config file.

**Comment by jaanjah** [comment]
First we need to add Slider, DropDownList and CheckBox features in https://github.com/Adrriii/Wobble, if it already exists there, then we can start working on this. (I haven't checked if it's already added thee, perhaps someone can check and respond here about it)
