### ISSUE TITLE
Map Select Viewing System

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#32]
The map select needs to display all the maps that it has read. Right now there are 3 options being discussed.

Card View - Provides more information for an individual map in one place, looks "modern". User scrolls from left to right. Doesn't work well with displaying basic info for multiple maps.
Design Concept from DusklyRefrain:
![image](https://user-images.githubusercontent.com/16842122/61921707-ea7f6380-af12-11e9-8c51-789f343e8cc3.png)

Scroll View - More traditional, this menu would be similar to games like osu! or DDR. User scrolls up or down. Basic information for non-selected maps is easier to see.
Example from osu: 
![image](https://user-images.githubusercontent.com/16842122/61921776-20bce300-af13-11e9-99ed-e0d5c9e4c0f1.png)

Tile View with Info Window- Using a similar system found in Intralism and SDVX, but with space dedicated to map details separate from the select menu. Interesting style, but maybe not the most intuitive. Displaying maps is a little trickier than a linear view, maybe less intuitive. Dedicated room for info without the downside of Card view. Basic info could be attached to the tiles.
Example from sdvx:
![image](https://user-images.githubusercontent.com/16842122/61921829-52ce4500-af13-11e9-98af-1fa285cebfa3.png)
Design Concept from Makaii: 
![image](https://user-images.githubusercontent.com/16842122/61921851-69749c00-af13-11e9-815f-6a43c16ccb9f.png)

**Comment by jaanjah** [comment]
Perhaps the required info can be read from the file's metadata. I think @Adrriii can work on adding the required data into the `.psc` files or whatever the file extension was.

**Comment by dustdustinthewind** [comment]
Some metadata work has been started on already, I probably should have clarified that. Adri's `.psc` includes

`Title
Artist
Mapper
Version
Audio`

As categories that could be used for sorting, well maybe not `Audio` lol

**Comment by Adrriii** [comment]
Yes, maybe not audio x)

If you have other ideas for metadata say it. Also we can sort by difficulty when we have a calculation.

**Comment by dustdustinthewind** [comment]
Map length, genre of the song, are the two things that come to mind. Length could probably be determined without metadata but genre/tags on a song would be set by the mapper. You should be able to extract genre from intralism maps too, iirc

**Comment by jaanjah** [comment]
In osu!, the .osz files are essentially just folders with content inside, I think we could so something like that, because that would allow for much customization later on.

**Comment by Adrriii** [comment]
yup that's what i had in mind, for now i didn't add a way of sharing psc maps since we don't have an editor or such
