### ISSUE TITLE
Editor View

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#33]
The editor needs to display all events it read from a map file. Right now there are 3 options being discussed. While having multiple views would be a great addition to the editor, we should focus on developing one before trying to integrate others.
In my opinion, Track View should be developed first. There are other references such as the o!m editor to take inspiration from, is relatively intuitive, and seems to be the easiest to develop. After creating the basics for this view, other views could be tried.
Edit: Gameplay view may not be as hard to create as I assumed: https://github.com/PulsarcGame/Pulsarc/issues/33#issuecomment-515415954

**Gameplay view** - This view replicates the playfield, with lines to determine beat snap. This would probably be the most intuitive style for the user, but could be complicated to design.
Design Concept: TBA

**Track View** - This view is similar to the osu!mania editor, having 4 tracks to represent the 4 directions arcs come from. Due to the nature of arcs, we should be careful how we lay out the tracks. While this may add more work, I think one way to improve this design is to give the user the ability to switch tracks around to what arc they prefer. If they think the tracks should be organized like "Up, Left, Right, Down" or "Down, Up, Left, Right", they should have the ability to set that. If they decide to switch positions of the tracks in the editor, it should not effect the arcs in the beatmap file.
osu!mania's editor:
![image](https://user-images.githubusercontent.com/16842122/61922122-41396d00-af14-11e9-9ec5-f14ab93b1dd5.png)

**Timeline view** - This view would be similar to the Intralism editor. It's not very intuitive, and is hard to display information well, but it could be an option for those used to Intralism's editor, and doesn't have the same organizational issue that Track View has. There are ways to make this more appealing and inuitive than Intralism's editor.
Intralism's editor:
![20190605001600_1](https://user-images.githubusercontent.com/16842122/61922150-57dfc400-af14-11e9-9cad-d3b870d78a9d.jpg)

**Comment by Adrriii** [comment]
Gameplay view ;

Not as hard as you would imagine. We can already scroll with the mouse wheel in a map while keeping the audio in sync thanks to Wobble.

The editor done this way would just be an extension of the GameplayEngine view adding features like : 
- BPM finder
- BPM snapping
- Add notes to the snaps
- Livemapping (snapped or unsnapped)
- and so on

**Comment by dustdustinthewind** [comment]
Fair enough, I'm not as familiar with the code as you are. I knew about the scrolling, I just assume it'd be harder to turn that into an editor than it would be to make a Track View from scratch.

**Comment by dustdustinthewind** [comment]
I've decided on Gameplay View for the first Editor view, closing this issue, for future views we'll make issues for each one.
