### ISSUE TITLE
Improve Arcs Movement

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#36]
Right now arcs move similarly, but not exactly to Intralism. They feel weird and not don't move quite like I think we want them to. Also, the code to determine the scrolling of arcs is using "Magic Numbers,", we're not exactly sure why they work.

If I've been understanding the code correctly, `HitObject.getDistanceToCrosshair()` and `HitObject.getSizeFromDistanceToCrosshair` are what needs to be fixed up.

Arc movement can be simplified like this:
Full Size Arc to Half-Size Arc takes x seconds
Half-Size Arc to Quarter-Size takes 2x seconds
Quarter to Eighth takes 4x seconds, etc.

Intralism Example: https://youtu.be/1LZm6rr2XIs

**Comment by Adrriii** [comment]
What do you mean by Full size, Half Size etc ?

The current functions are the following : 
getDistanceToCrosshair : Determine how far the arc should be depending on the current time
getSizeFromDistanceToCrosshair : Determine the size of the cut sprite anchored in the center to get the wanted distance

**Comment by jaanjah** [comment]
I think he meant how big the arc looks on screen, aka how close it is to crosshair.

**Comment by dustdustinthewind** [comment]
@Adrriii Here's a video demonstration, added it to first message. https://youtu.be/1LZm6rr2XIs

**Comment by Adrriii** [comment]
nice video

could you turn these timestamps into a formula ?
