### ISSUE TITLE
Cleaning and commenting of all the code

### ISSUE THREAD

**Issue by Adrriii** [PulsarcGame/Pulsarc#37]
We need to do this before merging to master as it is now ready for basic playing.

**Comment by jaanjah** [comment]
Are you working on this atm, or do you want to finish some other stuff up first?

If you could add what features must be finished before doing this would be great! :)

Also I think i should be able to finish this PR: https://github.com/PulsarcGame/Pulsarc/pull/5 after this issue gets solved.

**Comment by Adrriii** [comment]
This is more of something i'm working on each time i'm revisiting a file. Not actively on it.

**Comment by dustdustinthewind** [comment]
I've begun working on commenting on the code that (I think) I understand. I've been using `/// <summary>` since it seems that's useful for work in Visual Studio. If you look over it please let me know what can be improved!

https://github.com/PulsarcGame/Pulsarc/tree/Documentation

Keeping it on another Branch for now.

**Comment by Adrriii** [comment]
I've added comments to your latest commit
https://github.com/PulsarcGame/Pulsarc/commit/d70f8fa5b084d7e9862f1d990fdd728a7eb5ccc9

**Comment by jaanjah** [comment]
> I've begun working on commenting on the code that (I think) I understand. I've been using `/// <summary>` since it seems that's useful for work in Visual Studio. If you look over it please let me know what can be improved!
> 
> https://github.com/PulsarcGame/Pulsarc/tree/Documentation
> 
> Keeping it on another Branch for now.

Perhaps use WIP: tag and make a pull request so it would be easier to review code.

**Comment by dustdustinthewind** [comment]
I've been occasionally going through the code base and doing this very thing. I think we can close this now.
