### ISSUE TITLE
Fill readme.md and contribute.md

### ISSUE THREAD

**Issue by Adrriii** [PulsarcGame/Pulsarc#38]
the readme should contain how to convert beatmaps and play

**Comment by dustdustinthewind** [comment]
Added some instructions to #5
I think I got everything, I was a little confused what you meant x) Lemme know if there's anything I missed or if the readme needs anything changed.

**Comment by jaanjah** [comment]
Can this be closed? Looks like everything necessary got added to https://github.com/PulsarcGame/Pulsarc/pull/5

**Comment by Adrriii** [comment]
Not really, since now we have config.ini which will then be replaced by a settings menu (but not soon unless we do amazingly)

**Comment by jaanjah** [comment]
Thanks for responding, I was just asking since there had been no response for 11 days :)
