### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by jaanjah** [PulsarcGame/Pulsarc#45]
CHANGELOG should be added to keep track what are the new changes/fixes with each release.

I think this could be a great improvement.

I suggest following this [guide](https://keepachangelog.com/en/1.0.0/) when creating `CHANGELOG.md` and I think it'd make sense if we used [Semantic Versioning](https://semver.org/)

**Comment by dustdustinthewind** [comment]
The Changelog sounds like a great idea, I'll work on a change log and get it prepared by next release.
And yeah, Semantic Versioning is what I plan to use. However, looking back at release 1.0.1-a, I think I labelled it wrong, it should've been 1.1.0-a, right? It was more about adding stuff than it was about bug-fixes after all. Oh well, we'll get it right in future releases!

Thank you for the suggestions!

**Comment by jaanjah** [comment]
Looks like you decided to commit straight to `develop` branch.

This commit adds `CHANGELOG.md`: https://github.com/PulsarcGame/Pulsarc/commit/dc2ed37e1527414d44f79c46ad3d5426235400c1
