### ISSUE TITLE
Frame drops with with high FPSLimit

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#59]
Edit: It likely wasn't a problem of AMD/Ryzen CPUs but rather [the way we handle frame-rate control in the code](https://github.com/PulsarcGame/Pulsarc/issues/59#issuecomment-587686691).

I'm not exactly sure if this is only and issue with AMD CPU's or not, but 2 users have reported bad frame stutters and both use AMD CPUs. I'll be looking into it later, but I presume there is an issue with how we are multi-threading

Users' CPUs:
AMD Ryzen 5 1600 (6 cores / 12 threads)
AMD Ryzen 7 2700x (8 cores / 16 threads)

The Ryzen 7 user sent me this video, which uses a tool to show CPU usage data. https://drive.google.com/file/d/1y1Qq51D5cj1Vg-CQOOrTxhiixNNBtcis/view?usp=sharing
I did notice there were consistent spikes to 100% on multiple threads throughout the video, and you can see some spikes where Pulsarc's in-game fps counter drops to 500 or less. I'm not sure what to make out of the CPU data I don't know what should be "normal" or not but I'll look into it.

**Comment by Adrriii** [comment]
To check this we would need to add a way to disable multi threading, if that would help their case.

But i'm not sure what does using an amd cpu change, we're only at software level so it should behave the same after compile

**Comment by dustdustinthewind** [comment]
Other user was a ryzen 7 2700x, which has 8 cores, 16 threads. He mentioned that Ryzen's have had issues with ram, but looking into it it seems to be an issue more with the 1xxx series and either way I don't think this is a ram accessing problem we have.

> we're only at software level so it should behave the same after compile

That's what I'd assume too. But the frame stutters are a real issue. Something is happening.

**Comment by dustdustinthewind** [comment]
Did some more research and it's more likely that using `IsFixedTimeStep` and `TargetElapsedTime` with a high FPSLimit is causing these issues. Ryzen CPUs still could be influencing this bug to be worse but I don't think they're as related to the frame-stutter issue as originally thought.

More Info on FixedTimeStep with high framerates: https://github.com/MonoGame/MonoGame/issues/5783#issuecomment-309578731

**Comment by dustdustinthewind** [comment]
Confirmed from both the users have no stuttering after setting `FPSLimit` to 0, (which disables FixedTimeStep) one of them is going to keep using `FPSLimit = 0` for a few days and see if it's consistent over time and see how it affects his gameplay. Seems like we've found the culprit.

Whether or not this is causing the stuttering, I'll look for other ways to limit fps for one of the next updates, after this research it doesn't seem like using `IsFixedTimeStep` is optimal for us.

**Comment by dustdustinthewind** [comment]
https://github.com/PulsarcGame/MonoGame/commit/8b134f1ddeba3c1ea3c1b07ceb92dd39d6e292b6 fixes frame stuttering by reverting a change Wobble had made to MonoGame. The change Wobble had blocked access to the [improved accuracy of the timer for for fixed time step introduced in MonoGame 3.7.1](https://github.com/MonoGame/MonoGame/pull/6535). The improved timer accuracy fixes most or all of the times that using `IsFixedTimeStep` and `TargetElapsedTime` caused before.

I don't know the reason that Wobble blocked access, perhaps there is an issue I am unaware of that they fixed by using the imprecise timer. For now the commit seems to work based on some testing with one of the users who was experiencing this issue.

It is possible that frame stutter issues can be a problem for users who can't reach the 1000 fps limit, or hover around 1000 fps, but they should be able to fix the issue by turning off the fps cap or lowering the fps cap to something below their average. Idk for sure yet if this will be an issue, but based on my knowledge on how MonoGame handles this I think could be.
